# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Generator_Dialog(object):
    def setupUi(self, Generator_Dialog):
        Generator_Dialog.setObjectName("Generator_Dialog")
        Generator_Dialog.resize(971, 531)
        self.label = QtWidgets.QLabel(Generator_Dialog)
        self.label.setGeometry(QtCore.QRect(200, 0, 541, 121))
        self.label.setStyleSheet("font: 36pt \"黑体\";\n"
"color:rgb(255, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Generator_Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 941, 89))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label_2 = QtWidgets.QLabel(Generator_Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 210, 111, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Generator_Dialog)
        self.label_3.setGeometry(QtCore.QRect(710, 210, 111, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Generator_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Generator_Dialog)

    def retranslateUi(self, Generator_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Generator_Dialog.setWindowTitle(_translate("Generator_Dialog", "Dialog"))
        self.label.setText(_translate("Generator_Dialog", "素描图象生成器"))
        self.pushButton.setText(_translate("Generator_Dialog", "选择图片"))
        self.pushButton_2.setText(_translate("Generator_Dialog", "开始"))
        self.pushButton_3.setText(_translate("Generator_Dialog", "保存"))
        self.label_2.setText(_translate("Generator_Dialog", "原图像"))
        self.label_3.setText(_translate("Generator_Dialog", "素描图"))
