# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Insert_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Insert_Dialog(object):
    def setupUi(self, Insert_Dialog):
        Insert_Dialog.setObjectName("Insert_Dialog")
        Insert_Dialog.resize(477, 370)
        self.widget = QtWidgets.QWidget(Insert_Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font: 28pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("background-color:#FFFFFF;\n"
"height:40px;\n"
"font: 25 18pt \"等线 Light\";\n"
"border:1px solid #00FF00;\n"
"border-radius:25px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("background-color:#FFFFFF;\n"
"height:40px;\n"
"font: 25 18pt \"等线 Light\";\n"
"border:1px solid #00FF00;\n"
"border-radius:25px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Insert_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Insert_Dialog)

    def retranslateUi(self, Insert_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Insert_Dialog.setWindowTitle(_translate("Insert_Dialog", "录入"))
        self.label.setText(_translate("Insert_Dialog", "录入数据"))
        self.label_2.setText(_translate("Insert_Dialog", "姓名"))
        self.label_3.setText(_translate("Insert_Dialog", "学号"))
        self.label_4.setText(_translate("Insert_Dialog", "院系"))
        self.pushButton.setText(_translate("Insert_Dialog", "确认"))
        self.pushButton_2.setText(_translate("Insert_Dialog", "导入"))
