# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_KaoQin_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KaoQin_Dialog(object):
    def setupUi(self, KaoQin_Dialog):
        KaoQin_Dialog.setObjectName("KaoQin_Dialog")
        KaoQin_Dialog.resize(1061, 749)
        self.widget = QtWidgets.QWidget(KaoQin_Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 10, 991, 711))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 28pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(230)
        self.tableWidget.verticalHeader().setDefaultSectionSize(75)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(KaoQin_Dialog)
        QtCore.QMetaObject.connectSlotsByName(KaoQin_Dialog)

    def retranslateUi(self, KaoQin_Dialog):
        _translate = QtCore.QCoreApplication.translate
        KaoQin_Dialog.setWindowTitle(_translate("KaoQin_Dialog", "考勤记录"))
        self.label.setText(_translate("KaoQin_Dialog", "考勤记录"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("KaoQin_Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("KaoQin_Dialog", "考勤轮次"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("KaoQin_Dialog", "时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("KaoQin_Dialog", "操作"))
