# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_KaoQin_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KaoQin_Dialog(object):
    def setupUi(self, KaoQin_Dialog):
        KaoQin_Dialog.setObjectName("KaoQin_Dialog")
        KaoQin_Dialog.resize(1061, 749)
        self.widget = QtWidgets.QWidget(KaoQin_Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 10, 991, 711))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 28pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(KaoQin_Dialog)
        QtCore.QMetaObject.connectSlotsByName(KaoQin_Dialog)

    def retranslateUi(self, KaoQin_Dialog):
        _translate = QtCore.QCoreApplication.translate
        KaoQin_Dialog.setWindowTitle(_translate("KaoQin_Dialog", "考勤记录"))
        self.label.setText(_translate("KaoQin_Dialog", "考勤记录"))
