# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_User_Alter_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_Alter_Dialog(object):
    def setupUi(self, User_Alter_Dialog):
        User_Alter_Dialog.setObjectName("User_Alter_Dialog")
        User_Alter_Dialog.resize(447, 385)
        self.widget = QtWidgets.QWidget(User_Alter_Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 411, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font: 28pt \"黑体\";\n"
"color:rgb(255, 0, 0)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font: 25 18pt \"等线 Light\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(18)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("background:rgb(251, 255, 242);\n"
"border: 0px;\n"
"border-radius:20px;\n"
"font: 18pt \"Agency FB\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(User_Alter_Dialog)
        QtCore.QMetaObject.connectSlotsByName(User_Alter_Dialog)

    def retranslateUi(self, User_Alter_Dialog):
        _translate = QtCore.QCoreApplication.translate
        User_Alter_Dialog.setWindowTitle(_translate("User_Alter_Dialog", "修改用户资料"))
        self.label_4.setText(_translate("User_Alter_Dialog", "修改资料"))
        self.label.setText(_translate("User_Alter_Dialog", "名字"))
        self.label_2.setText(_translate("User_Alter_Dialog", "学号"))
        self.label_3.setText(_translate("User_Alter_Dialog", "院系"))
        self.pushButton.setText(_translate("User_Alter_Dialog", "确认"))
