# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_User_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_Dialog(object):
    def setupUi(self, User_Dialog):
        User_Dialog.setObjectName("User_Dialog")
        User_Dialog.resize(1061, 749)
        self.layoutWidget = QtWidgets.QWidget(User_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 991, 711))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 28pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(User_Dialog)
        QtCore.QMetaObject.connectSlotsByName(User_Dialog)

    def retranslateUi(self, User_Dialog):
        _translate = QtCore.QCoreApplication.translate
        User_Dialog.setWindowTitle(_translate("User_Dialog", "Dialog"))
        self.label.setText(_translate("User_Dialog", "用户数据"))
